# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SplitLine
                                 A QGIS plugin
 Split the line in parts on the basis of user provided distance.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-11
        copyright            : (C) 2021 by Ram Kumar K
        email                : ragukulathilak@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SplitLine class from file SplitLine.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .split_line import SplitLine
    return SplitLine(iface)
